#!/usr/bin/env bash

# Configuration and various settings
bspc config focus_follows_pointer true
bspc config pointer_follows_focus true
bspc config pointer_follows_monitor true
bspc config gapless_monocle true
bspc config single_monocle true
bspc config window_gap 4
bspc config border_width 2

# Monitor configurations
bspc monitor ^1 -d 1 2 3 4 5 6 7 8 9
bspc monitor ^2 -d 0

# Window rules
bspc rule -a Emacs state=tiled

# Startup applications and scripts
pgrep -x sxhkd || sxhkd &
pgrep -x polybar || polybar &
pgrep -x .dunst-wrapped || dunst &
flameshot &
~/.fehbg
pgrep -x .light-locker-w || light-locker --lock-on-lid &
